# Problem configuration, version 1.0 
# PC^2 Version: Version 9 () Java ver 1.8.0_25 build  Windows 7 6.1 (amd64) 
# Created: 2017-08-07 20:11:15 PDT
--- 

name: 'I Sumit stdin Comp+Man clics D1'
source: 
author: 
license: 
rights_owner: 

groups: 'Canada - University of British Columbia D1;Puget Sound - University of Puget Sound D1; N. California - UC Berkeley D1; Hawaii - BYUH, Laie, Oahu D1; Northeast - EWU, Cheney/Spokane D1;'


load-data-files: false

datafile: sumit.in
datafile: sumit.ans

# validator_flags: 

limits:
    timeout: 30

validator: 
    validatorProg: 'edu.csus.ecs.pc2.validator.clicsValidator.ClicsValidator'
    validatorCmd: '{:validator} {:infile} {:ansfile} {:feedbackdir} '
    usingInternal: false
    validatorOption: 1

    use-internal-validator: false

judging-type:
    computer-judged: true
    manual-review: true
    send-prelim-judgement: true

input:
    readFromSTDIN: true

#     wrote (D)c:/tmp/valtest/sumit/data/secret/sumit.in
#     wrote (D)c:/tmp/valtest/sumit/data/secret/sumit1.in
#     wrote (D)c:/tmp/valtest/sumit/data/secret/sumit2.in
#     wrote (D)c:/tmp/valtest/sumit/data/secret/sumit3.in
#     wrote (D)c:/tmp/valtest/sumit/data/secret/sumit4.in
#     wrote (D)c:/tmp/valtest/sumit/data/secret/sumit5.in
#     wrote (D)c:/tmp/valtest/sumit/data/secret/sumit6.in
#     wrote (A)c:/tmp/valtest/sumit/data/secret/sumit.ans
#     wrote (A)c:/tmp/valtest/sumit/data/secret/sumit1.ans
#     wrote (A)c:/tmp/valtest/sumit/data/secret/sumit2.ans
#     wrote (A)c:/tmp/valtest/sumit/data/secret/sumit3.ans
#     wrote (A)c:/tmp/valtest/sumit/data/secret/sumit4.ans
#     wrote (A)c:/tmp/valtest/sumit/data/secret/sumit5.ans
#     wrote (A)c:/tmp/valtest/sumit/data/secret/sumit6.ans

