# Contest Configuration, version 1.0 
# PC^2 Version: Version 9.3 20110918 (Sunday, September 18th 2011 23:51 UTC) Java ver 1.6.0_20 build 2345 Windows XP 5.1 (x86) 
# Created: 2011-09-18 18:05:40 PDT
# $HeadURL$
--- 

name: Sumit Hello Sample
short-name: 
elapsed: 0:00:00
remaining: 5:00:00
running: false
scoreboard-freeze: 

languages:
  - name: Java
    active: true

  - name: Perl
    active: true

  - name: GNU C++
    active: true

  - name: GNU C
    active: true

problemset:
  - letter: A
    short-name: hello
#     2 data files written
#     wrote reports\yaml09.18.40.546\hello\problem.yaml
#     wrote reports\yaml09.18.40.546\hello\data\secret\hello.ans

  - letter: B
    short-name: sumit
#     3 data files written
#     wrote reports\yaml09.18.40.546\sumit\problem.yaml
#     wrote reports\yaml09.18.40.546\sumit\data\secret\sumit.dat
#     wrote reports\yaml09.18.40.546\sumit\data\secret\sumit.ans

sites:
 - number: 1
   name: Site 1
   IP: localhost
   port: 50002

accounts:
  - account: TEAM
    site: 1
    count: 22

  - account: JUDGE
    site: 1
    count: 12

  - account: SCOREBOARD
    site: 1
    count: 1

# EOF Contest Configuration
